import { Injectable } from '@angular/core';

export type SupportedLanguage = 'en' | 'fr' | 'ar';

type Translations = Record<SupportedLanguage, Record<string, string>>;

const TRANSLATIONS: Translations = {
  en: {
    brandName: 'NABILOX CAR',
    navHome: 'Home',
    navAbout: 'About',
    navCars: 'Our Cars',
    navServices: 'Services',
    navReviews: 'Reviews',
    navContact: 'Contact',
    carsPageTitle: 'Our Cars',
    carsPageSubtitle: 'Browse our complete collection of rental vehicles',
    searchLabel: 'Search',
    searchPlaceholder: 'Search by brand or model...',
    brandLabel: 'Brand',
    allBrands: 'All Brands',
    fuelLabel: 'Fuel Type',
    allFuels: 'All Types',
    diesel: 'Diesel',
    essence: 'Essence',
    hybrid: 'Hybrid',
    transmissionLabel: 'Transmission',
    allTransmissions: 'All Types',
    automatic: 'Automatic',
    manual: 'Manual',
    resetFilters: 'Reset Filters',
    showing: 'Showing',
    vehicles: 'vehicles',
    noResultsTitle: 'No vehicles found',
    noResultsText: 'Try adjusting your filters or search terms',
    ctaTitle: 'Ready to Rent a Car?',
    ctaText: "Contact us now to book your preferred vehicle. We're available 24/7 to assist you.",
    btnWhatsApp: 'WhatsApp',
    perDay: '/day',
    phone: '+212 6 61 84 19 71',
    open24: 'Open 24/7',
    heroTitle: 'Reliable Car Rental in Rabat',
    heroSubtitle: 'Professional service available 24/7 - Your trusted partner for car rental in Morocco',
    btnCallNow: 'Call Now',
    btnBookCar: 'Book a Car',
    basedOn: 'Based on',
    feature1Title: '24/7 Service',
    feature1Desc: 'Always available',
    feature2Title: 'Professional Team',
    feature2Desc: 'Expert service',
    feature3Title: 'Excellent Reviews',
    feature3Desc: '4.8/5 rating',
    aboutTitle: 'About Nabilox Car',
    aboutText1: "Nabilox Car is a trusted and professional car rental agency based in Rabat, Morocco. We are committed to providing exceptional service to our customers, whether you're a tourist exploring Morocco, a business professional, or a local resident.",
    aboutText2: 'With our 24/7 availability and a fleet of well-maintained vehicles, we ensure that your transportation needs are always met with reliability and professionalism. Our excellent customer reviews speak to our dedication to quality service and customer satisfaction.',
    statRating: 'Rating',
    statAvailable: 'Available',
    statReviews: 'Reviews',
    statSatisfaction: 'Satisfaction',
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Professional car rental solutions for every need',
    service1Title: 'Short & Long Term Rental',
    service1Desc: 'Flexible rental options from daily to monthly periods, tailored to your specific needs.',
    service2Title: 'Tourist Rentals',
    service2Desc: 'Perfect solutions for tourists exploring Morocco with comfortable and reliable vehicles.',
    service3Title: 'Business Rentals',
    service3Desc: 'Professional car rental services for business travelers and corporate clients.',
    service4Title: 'Family Vehicles',
    service4Desc: 'Spacious and comfortable vehicles perfect for family trips and group travel.',
    service5Title: '24/7 Availability',
    service5Desc: 'Round-the-clock service to meet your transportation needs at any time.',
    service6Title: 'Local Expertise',
    service6Desc: 'Expert knowledge of Rabat and Morocco to help you navigate with confidence.',
    reviewsTitle: 'Customer Reviews',
    review1: 'Très bon service, je recommande vivement… la meilleure agence de location au Maroc.',
    review2: 'Très bonne expérience, très bonne équipe.',
    review3: 'Service excellent, très professionnel et respectueux.',
    reviewer1: 'Customer Review',
    reviewer2: 'Customer Review',
    reviewer3: 'Customer Review',
    contactTitle: 'Contact Us',
    contactSubtitle: 'Get in touch with us for your car rental needs',
    contactInfoTitle: 'Contact Information',
    phoneLabel: 'Phone',
    addressLabel: 'Address',
    hoursLabel: 'Opening Hours',
    hours: 'Open 24/7',
    ratingLabel: 'Rating',
    formTitle: 'Send us a message',
    namePlaceholder: 'Your Name',
    emailPlaceholder: 'Your Email',
    phonePlaceholder: 'Your Phone',
    messagePlaceholder: 'Your Message',
    btnSend: 'Send Message',
    footerDesc: 'Your trusted car rental partner in Rabat, Morocco. Professional service available 24/7.',
    footerQuickLinks: 'Quick Links',
    footerContact: 'Contact',
    footerRights: 'All rights reserved.',
    year: 'Year',
    seats: 'Seats',
    fuelType: 'Fuel',
    transmissionType: 'Transmission',
    bookNow: 'Book Now',
    details: 'Details',
    carsShowcase: 'OUR CARS'
  },
  fr: {
    brandName: 'NABILOX CAR',
    navHome: 'Accueil',
    navAbout: 'À Propos',
    navCars: 'Nos Voitures',
    navServices: 'Services',
    navReviews: 'Avis',
    navContact: 'Contact',
    carsPageTitle: 'Nos Voitures',
    carsPageSubtitle: 'Parcourez notre collection complète de véhicules de location',
    searchLabel: 'Rechercher',
    searchPlaceholder: 'Rechercher par marque ou modèle...',
    brandLabel: 'Marque',
    allBrands: 'Toutes les Marques',
    fuelLabel: 'Type de Carburant',
    allFuels: 'Tous les Types',
    diesel: 'Diesel',
    essence: 'Essence',
    hybrid: 'Hybride',
    transmissionLabel: 'Transmission',
    allTransmissions: 'Tous les Types',
    automatic: 'Automatique',
    manual: 'Manuelle',
    resetFilters: 'Réinitialiser les Filtres',
    showing: 'Affichage de',
    vehicles: 'véhicules',
    noResultsTitle: 'Aucun véhicule trouvé',
    noResultsText: "Essayez d'ajuster vos filtres ou termes de recherche",
    ctaTitle: 'Prêt à Louer une Voiture?',
    ctaText: 'Contactez-nous maintenant pour réserver votre véhicule préféré. Nous sommes disponibles 24h/24 pour vous aider.',
    btnWhatsApp: 'WhatsApp',
    perDay: '/jour',
    phone: '+212 6 61 84 19 71',
    open24: 'Ouvert 24h/24',
    heroTitle: 'Location de Voiture Fiable à Rabat',
    heroSubtitle: 'Service professionnel disponible 24h/24 - Votre partenaire de confiance pour la location de voiture au Maroc',
    btnCallNow: 'Appelez Maintenant',
    btnBookCar: 'Réserver une Voiture',
    basedOn: 'Basé sur',
    feature1Title: 'Service 24h/24',
    feature1Desc: 'Toujours disponible',
    feature2Title: 'Équipe Professionnelle',
    feature2Desc: 'Service expert',
    feature3Title: 'Excellents Avis',
    feature3Desc: 'Note 4.8/5',
    aboutTitle: 'À Propos de Nabilox Car',
    aboutText1: 'Nabilox Car est une agence de location de voitures professionnelle et de confiance basée à Rabat, au Maroc. Nous nous engageons à fournir un service exceptionnel à nos clients, que vous soyez un touriste explorant le Maroc, un professionnel ou un résident local.',
    aboutText2: 'Avec notre disponibilité 24h/24 et une flotte de véhicules bien entretenus, nous garantissons que vos besoins en transport sont toujours satisfaits avec fiabilité et professionnalisme. Nos excellents avis clients témoignent de notre engagement envers un service de qualité et la satisfaction client.',
    statRating: 'Note',
    statAvailable: 'Disponible',
    statReviews: 'Avis',
    statSatisfaction: 'Satisfaction',
    servicesTitle: 'Nos Services',
    servicesSubtitle: 'Solutions de location professionnelles pour tous les besoins',
    service1Title: 'Location Courte & Longue Durée',
    service1Desc: 'Options de location flexibles de la journée au mois, adaptées à vos besoins spécifiques.',
    service2Title: 'Locations Touristiques',
    service2Desc: 'Solutions parfaites pour les touristes explorant le Maroc avec des véhicules confortables et fiables.',
    service3Title: 'Locations Professionnelles',
    service3Desc: "Services de location de voitures professionnels pour les voyageurs d'affaires et les clients corporatifs.",
    service4Title: 'Véhicules Familiaux',
    service4Desc: 'Véhicules spacieux et confortables parfaits pour les voyages en famille et en groupe.',
    service5Title: 'Disponibilité 24h/24',
    service5Desc: 'Service 24h/24 pour répondre à vos besoins de transport à tout moment.',
    service6Title: 'Expertise Locale',
    service6Desc: 'Connaissance experte de Rabat et du Maroc pour vous aider à naviguer en toute confiance.',
    reviewsTitle: 'Avis Clients',
    review1: 'Très bon service, je recommande vivement… la meilleure agence de location au Maroc.',
    review2: 'Très bonne expérience, très bonne équipe.',
    review3: 'Service excellent, très professionnel et respectueux.',
    reviewer1: 'Avis Client',
    reviewer2: 'Avis Client',
    reviewer3: 'Avis Client',
    contactTitle: 'Contactez-Nous',
    contactSubtitle: 'Contactez-nous pour vos besoins de location de voiture',
    contactInfoTitle: 'Informations de Contact',
    phoneLabel: 'Téléphone',
    addressLabel: 'Adresse',
    hoursLabel: "Heures d'Ouverture",
    hours: 'Ouvert 24h/24',
    ratingLabel: 'Note',
    formTitle: 'Envoyez-nous un message',
    namePlaceholder: 'Votre Nom',
    emailPlaceholder: 'Votre Email',
    phonePlaceholder: 'Votre Téléphone',
    messagePlaceholder: 'Votre Message',
    btnSend: 'Envoyer le Message',
    footerDesc: 'Votre partenaire de confiance pour la location de voiture à Rabat, Maroc. Service professionnel disponible 24h/24.',
    footerQuickLinks: 'Liens Rapides',
    footerContact: 'Contact',
    footerRights: 'Tous droits réservés.',
    year: 'Année',
    seats: 'Places',
    fuelType: 'Carburant',
    transmissionType: 'Transmission',
    bookNow: 'Réserver',
    details: 'Détails',
    carsShowcase: 'NOS VOITURES'
  },
  ar: {
    brandName: 'نبيلوكس كار',
    navHome: 'الرئيسية',
    navAbout: 'من نحن',
    navCars: 'سياراتنا',
    navServices: 'الخدمات',
    navReviews: 'التقييمات',
    navContact: 'اتصل بنا',
    carsPageTitle: 'سياراتنا',
    carsPageSubtitle: 'تصفح مجموعتنا الكاملة من المركبات المتاحة للإيجار',
    searchLabel: 'بحث',
    searchPlaceholder: 'البحث حسب العلامة التجارية أو الطراز...',
    brandLabel: 'العلامة التجارية',
    allBrands: 'جميع العلامات التجارية',
    fuelLabel: 'نوع الوقود',
    allFuels: 'جميع الأنواع',
    diesel: 'ديزل',
    essence: 'بنزين',
    hybrid: 'هجين',
    transmissionLabel: 'ناقل الحركة',
    allTransmissions: 'جميع الأنواع',
    automatic: 'أوتوماتيك',
    manual: 'يدوي',
    resetFilters: 'إعادة تعيين الفلاتر',
    showing: 'عرض',
    vehicles: 'مركبات',
    noResultsTitle: 'لم يتم العثور على مركبات',
    noResultsText: 'حاول تعديل الفلاتر أو مصطلحات البحث',
    ctaTitle: 'هل أنت مستعد لاستئجار سيارة؟',
    ctaText: 'اتصل بنا الآن لحجز سيارتك المفضلة. نحن متاحون على مدار الساعة لمساعدتك.',
    btnWhatsApp: 'واتساب',
    perDay: '/يوم',
    phone: '+212 6 61 84 19 71',
    open24: 'مفتوح 24/7',
    heroTitle: 'تأجير سيارات موثوق في الرباط',
    heroSubtitle: 'خدمة احترافية متاحة على مدار الساعة - شريكك الموثوق لتأجير السيارات في المغرب',
    btnCallNow: 'اتصل الآن',
    btnBookCar: 'احجز سيارة',
    basedOn: 'بناءً على',
    feature1Title: 'خدمة 24/7',
    feature1Desc: 'متاح دائماً',
    feature2Title: 'فريق محترف',
    feature2Desc: 'خدمة متخصصة',
    feature3Title: 'تقييمات ممتازة',
    feature3Desc: 'تقييم 4.8/5',
    aboutTitle: 'عن نبيلوكس كار',
    aboutText1: 'نبيلوكس كار هي وكالة تأجير سيارات موثوقة ومحترفة مقرها في الرباط، المغرب. نحن ملتزمون بتقديم خدمة استثنائية لعملائنا، سواء كنت سائحاً يستكشف المغرب، أو محترفاً في مجال الأعمال، أو مقيماً محلياً.',
    aboutText2: 'مع توفرنا على مدار الساعة وأسطول من المركبات المُصانة جيداً، نضمن تلبية احتياجاتك في النقل دائماً بموثوقية واحترافية. تقييمات عملائنا الممتازة تشهد على التزامنا بالخدمة عالية الجودة ورضا العملاء.',
    statRating: 'التقييم',
    statAvailable: 'متاح',
    statReviews: 'التقييمات',
    statSatisfaction: 'الرضا',
    servicesTitle: 'خدماتنا',
    servicesSubtitle: 'حلول تأجير سيارات احترافية لكل احتياج',
    service1Title: 'تأجير قصير وطويل الأمد',
    service1Desc: 'خيارات تأجير مرنة من يومية إلى شهرية، مصممة خصيصاً لاحتياجاتك.',
    service2Title: 'تأجير سياحي',
    service2Desc: 'حلول مثالية للسياح الذين يستكشفون المغرب بمركبات مريحة وموثوقة.',
    service3Title: 'تأجير للأعمال',
    service3Desc: 'خدمات تأجير سيارات احترافية لرجال الأعمال والعملاء من الشركات.',
    service4Title: 'مركبات عائلية',
    service4Desc: 'مركبات واسعة ومريحة مثالية للرحلات العائلية والسفر الجماعي.',
    service5Title: 'متاح 24/7',
    service5Desc: 'خدمة على مدار الساعة لتلبية احتياجاتك في النقل في أي وقت.',
    service6Title: 'خبرة محلية',
    service6Desc: 'معرفة متخصصة بالرباط والمغرب لمساعدتك على التنقل بثقة.',
    reviewsTitle: 'آراء العملاء',
    review1: 'خدمة جيدة جداً، أوصي بشدة... أفضل وكالة تأجير في المغرب.',
    review2: 'تجربة جيدة جداً، فريق ممتاز.',
    review3: 'خدمة ممتازة، محترفة جداً ومحترمة.',
    reviewer1: 'تقييم العميل',
    reviewer2: 'تقييم العميل',
    reviewer3: 'تقييم العميل',
    contactTitle: 'اتصل بنا',
    contactSubtitle: 'تواصل معنا لاحتياجاتك في تأجير السيارات',
    contactInfoTitle: 'معلومات الاتصال',
    phoneLabel: 'الهاتف',
    addressLabel: 'العنوان',
    hoursLabel: 'ساعات العمل',
    hours: 'مفتوح 24/7',
    ratingLabel: 'التقييم',
    formTitle: 'أرسل لنا رسالة',
    namePlaceholder: 'اسمك',
    emailPlaceholder: 'بريدك الإلكتروني',
    phonePlaceholder: 'هاتفك',
    messagePlaceholder: 'رسالتك',
    btnSend: 'إرسال الرسالة',
    footerDesc: 'شريكك الموثوق لتأجير السيارات في الرباط، المغرب. خدمة احترافية متاحة على مدار الساعة.',
    footerQuickLinks: 'روابط سريعة',
    footerContact: 'اتصل بنا',
    footerRights: 'جميع الحقوق محفوظة.',
    year: 'السنة',
    seats: 'المقاعد',
    fuelType: 'الوقود',
    transmissionType: 'ناقل الحركة',
    bookNow: 'احجز الآن',
    details: 'التفاصيل',
    carsShowcase: 'سياراتنا'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  currentLang: SupportedLanguage = 'fr';

  initializeLanguage(): void {
    const saved = localStorage.getItem('preferredLanguage') as SupportedLanguage | null;
    const lang = saved && ['en', 'fr', 'ar'].includes(saved) ? saved : 'fr';
    this.setLanguage(lang);
  }

  setLanguage(lang: SupportedLanguage): void {
    this.currentLang = lang;
    const html = document.documentElement;
    html.setAttribute('lang', lang);
    html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    localStorage.setItem('preferredLanguage', lang);
    this.applyTranslations();
  }

  t(key: string): string {
    return TRANSLATIONS[this.currentLang]?.[key] ?? key;
  }

  applyTranslations(root: ParentNode = document): void {
    root.querySelectorAll('[data-translate]').forEach(element => {
      const key = element.getAttribute('data-translate') || '';
      const value = this.t(key);
      if (value !== key) {
        element.textContent = value;
      }
    });

    root.querySelectorAll('[data-translate-placeholder]').forEach(element => {
      const key = element.getAttribute('data-translate-placeholder') || '';
      const value = this.t(key);
      if (value !== key) {
        element.setAttribute('placeholder', value);
      }
    });
  }
}
